# -*- coding: utf-8 -*-
"""Anomaly_ByClass_BySubject_Upload.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O8kwWV5S51qN4Co3lX3UABZkJih2QQLZ

# 🎓 Phát hiện điểm bất thường điểm số học sinh (Lớp & Môn)
"""

# === THAM SỐ PHÂN TÍCH ===
Z_THRESH = 2.0
REQUIRE_COLUMNS = ["MaHS", "HoTen", "Lop"]   # cột chuẩn sau khi map alias

VALIDATE_SCORES = True
SCORE_MIN, SCORE_MAX = 0.0, 10.0

# === HÀM TIỆN ÍCH ===
import re
import unicodedata
import numpy as np
import pandas as pd

def strip_accents(s: str) -> str:
    if not isinstance(s, str):
        s = str(s)
    s = unicodedata.normalize("NFD", s)
    s = "".join(ch for ch in s if unicodedata.category(ch) != "Mn")
    return s

def norm_col(s: str) -> str:
    """chuẩn hóa tên cột: bỏ dấu, thường hóa, bỏ khoảng trắng/ký tự lạ"""
    s = strip_accents(s)
    s = s.lower().strip()
    s = re.sub(r"[^a-z0-9]+", "_", s)      # thay mọi ký tự lạ bằng _
    s = re.sub(r"_+", "_", s).strip("_")
    return s

# Các alias hay gặp → ánh xạ về cột chuẩn
ALIAS_MAP = {
    # MaHS
    "mahs": "MaHS", "ma_hs": "MaHS", "studentid": "MaHS", "id": "MaHS", "mssv": "MaHS",

    # HoTen
    "hoten": "HoTen", "ho_ten": "HoTen", "ho_va_ten": "HoTen", "tenhs": "HoTen",
    "ten_hs": "HoTen", "studentname": "HoTen", "name": "HoTen",

    # Lop
    "lop": "Lop", "lop_hoc": "Lop", "class": "Lop", "class_name": "Lop", "ten_lop": "Lop"
}

def normalize_headers(df: pd.DataFrame) -> pd.DataFrame:
    """Đổi tên cột theo ALIAS_MAP → về cột chuẩn 'MaHS','HoTen','Lop' """
    mapping = {}
    for c in df.columns:
        key = norm_col(c)
        if key in ALIAS_MAP:
            mapping[c] = ALIAS_MAP[key]
    df = df.rename(columns=mapping)
    return df

def detect_score_columns(df: pd.DataFrame):
    """cột điểm = numeric, khác 3 cột định danh"""
    return [c for c in df.columns
            if c not in REQUIRE_COLUMNS and pd.api.types.is_numeric_dtype(df[c])]

def validate_scores(df: pd.DataFrame, score_cols):
    if not VALIDATE_SCORES:
        return df
    df = df.copy()
    for c in score_cols:
        df.loc[~df[c].between(SCORE_MIN, SCORE_MAX), c] = np.nan
    return df

def zscore_series(s: pd.Series) -> pd.Series:
    mu = s.mean(); sigma = s.std(ddof=0)
    if sigma == 0 or np.isnan(sigma):
        sigma = 1e-9
    return (s - mu) / sigma

def compute_anomalies(df: pd.DataFrame, z_thresh: float = 2.0):
    # 1) Chuẩn hóa header
    df = normalize_headers(df)

    # 2) Bắt buộc có 3 cột chuẩn; nếu thiếu 'HoTen' thì tạo tạm (không chặn)
    missing = list(set(REQUIRE_COLUMNS) - set(df.columns))
    if "HoTen" in missing and "MaHS" in df.columns:
        df["HoTen"] = df["MaHS"].astype(str)    # điền tạm = MaHS
        missing.remove("HoTen")
    if missing:  # còn thiếu gì khác (ví dụ 'Lop' hoặc 'MaHS') thì dừng
        raise ValueError(f"Thiếu cột bắt buộc: {missing}")

    # 3) Đảm bảo cột điểm là số
    for c in df.columns:
        if c not in REQUIRE_COLUMNS:
            df[c] = pd.to_numeric(df[c], errors="coerce")

    # 4) Xác định cột điểm
    score_cols = detect_score_columns(df)
    if not score_cols:
        raise ValueError("Không tìm thấy cột điểm số nào (các cột ngoài định danh không phải số).")

    # 5) Tính toán
    df = validate_scores(df, score_cols).copy()
    df["DiemTB"] = df[score_cols].mean(axis=1, skipna=True)
    df["Z_tb"] = zscore_series(df["DiemTB"])
    df["BT_TB"] = df["Z_tb"].abs() > z_thresh

    for c in score_cols:
        df[f"Z_{c}"] = zscore_series(df[c])
        df[f"BT_{c}"] = df[f"Z_{c}"].abs() > z_thresh

    by_class_tb = (df.groupby("Lop")
                     .agg(TongHS=("MaHS", "count"),
                          BatThuong=("BT_TB","sum"))
                     .reset_index())
    by_class_tb["TyLe_%"] = (by_class_tb["BatThuong"]/by_class_tb["TongHS"]*100).round(2)

    rows = []
    for c in score_cols:
        rows.append({"Mon": c,
                     "BatThuong": int(df[f"BT_{c}"].sum()),
                     "TongHS": int(df["MaHS"].count())})
    by_subject = pd.DataFrame(rows)
    by_subject["TyLe_%"] = (by_subject["BatThuong"]/by_subject["TongHS"]*100).round(2)

    return {
        "out_full": df,
        "by_class_tb": by_class_tb.sort_values("BatThuong", ascending=False),
        "by_subject": by_subject.sort_values("BatThuong", ascending=False),
        "score_cols": score_cols
    }

import io, os
import matplotlib.pyplot as plt

if use_colab:
    print("👉 Chọn 1 hoặc nhiều file CSV để upload")
    uploaded = files.upload()  # có thể chọn nhiều file
else:
    print("Không ở Colab. Gán 'uploaded' = {tên: bytes} nếu test local.")
    uploaded = {}

if uploaded:
    for fname, raw in uploaded.items():
        print("="*80)
        print("Phân tích:", fname)

        # Thử đọc nhiều encoding nếu cần
        df = None
        for enc in ["utf-8-sig", "utf-8", "cp1258", "latin-1"]:
            try:
                df = pd.read_csv(io.BytesIO(raw), encoding=enc)
                break
            except Exception:
                df = None
        if df is None:
            print("❌ Không đọc được CSV với các encoding phổ biến.")
            continue

        try:
            res = compute_anomalies(df, z_thresh=Z_THRESH)
        except Exception as e:
            print("❌ Lỗi tính toán:", e)
            continue

        out_full = res["out_full"]
        by_class_tb = res["by_class_tb"]
        by_subject = res["by_subject"]

        base = os.path.splitext(os.path.basename(fname))[0]
        out_full.to_csv(f"{base}__ket_qua_chi_tiet.csv", index=False, encoding="utf-8")
        by_class_tb.to_csv(f"{base}__tong_hop_theo_lop.csv", index=False, encoding="utf-8")
        by_subject.to_csv(f"{base}__tong_hop_theo_mon.csv", index=False, encoding="utf-8")

        display(by_class_tb)
        display(by_subject)

        # Biểu đồ
        plt.figure(); plt.title(f"Số HS bất thường theo LỚP (|Z_tb|>{Z_THRESH}) – {fname}")
        plt.xlabel("Lớp"); plt.ylabel("Số HS bất thường")
        plt.bar(by_class_tb["Lop"].astype(str), by_class_tb["BatThuong"])
        plt.xticks(rotation=45, ha="right"); plt.tight_layout(); plt.show()

        plt.figure(); plt.title(f"Tỷ lệ % bất thường theo LỚP – {fname}")
        plt.xlabel("Lớp"); plt.ylabel("Tỷ lệ (%)")
        plt.bar(by_class_tb["Lop"].astype(str), by_class_tb["TyLe_%"])
        plt.xticks(rotation=45, ha="right"); plt.tight_layout(); plt.show()

        plt.figure(); plt.title(f"Số HS bất thường theo MÔN (|Z_môn|>{Z_THRESH}) – {fname}")
        plt.xlabel("Môn"); plt.ylabel("Số HS bất thường")
        plt.bar(by_subject["Mon"].astype(str), by_subject["BatThuong"])
        plt.xticks(rotation=45, ha="right"); plt.tight_layout(); plt.show()

        mu = out_full["DiemTB"].mean(); sigma = out_full["DiemTB"].std(ddof=0)
        left = mu - Z_THRESH*(sigma if sigma!=0 else 1e-9)
        right = mu + Z_THRESH*(sigma if sigma!=0 else 1e-9)
        plt.figure(); plt.title(f"Phân phối DiemTB + ngưỡng Z (μ={mu:.2f}, σ={sigma:.2f}) – {fname}")
        plt.xlabel("DiemTB"); plt.ylabel("Tần suất")
        plt.hist(out_full["DiemTB"].dropna(), bins=20)
        plt.axvline(left, linestyle="--"); plt.axvline(right, linestyle="--")
        plt.tight_layout(); plt.show()
else:
    print("Chưa upload file.")